// Datos de las recetas saludables para pacientes con cáncer
// Se usa tanto en recetas.php (para el listado en grid) como en recetas-detalle.php (para el detalle paso a paso)
// La propiedad "publico" indica si la receta puede verse sin iniciar sesión (Recetas.N.php).
// Las recetas con publico:false solo se muestran/detallan a usuarios con sesión iniciada.
const recetasSaludables = [
  {
    id: 1,
    nombre: "Batido de plátano y avena",
    categoria: "Batidos y bebidas",
    publico: true,
    icono: "🍌",
    tiempo: "5 min",
    porciones: 1,
    dificultad: "Fácil",
    descripcion:
      "Batido suave y energizante, ideal para las mañanas con poco apetito.",
    beneficio:
      "Aporta energía de fácil digestión y ayuda a mantener el peso durante el tratamiento.",
    ingredientes: [
      "1 plátano maduro",
      "1/2 taza de avena cocida",
      "1 taza de leche (o bebida vegetal)",
      "1 cucharadita de miel",
      "Una pizca de canela",
    ],
    pasos: [
      "Cocina la avena en agua o leche hasta que esté suave y déjala enfriar.",
      "Coloca el plátano, la avena, la leche y la miel en la licuadora.",
      "Licúa hasta obtener una mezcla homogénea y sin grumos.",
      "Sirve en un vaso y espolvorea canela por encima.",
      "Toma el batido lentamente, a temperatura ambiente si hay sensibilidad al frío.",
    ],
  },
  {
    id: 2,
    nombre: "Sopa de zanahoria y jengibre",
    categoria: "Sopas y cremas",
    publico: true,
    icono: "🥕",
    tiempo: "25 min",
    porciones: 2,
    dificultad: "Fácil",
    descripcion:
      "Sopa reconfortante y suave que ayuda a calmar el estómago.",
    beneficio:
      "El jengibre es tradicionalmente usado para aliviar náuseas; la zanahoria aporta vitamina A.",
    ingredientes: [
      "4 zanahorias medianas, peladas y picadas",
      "1 cucharadita de jengibre fresco rallado",
      "1/2 cebolla picada",
      "2 tazas de caldo de vegetales bajo en sodio",
      "1 cucharada de aceite de oliva",
      "Sal al gusto (moderada)",
    ],
    pasos: [
      "Calienta el aceite de oliva en una olla a fuego medio y sofríe la cebolla hasta que esté transparente.",
      "Agrega la zanahoria y el jengibre, y cocina por 2 minutos moviendo constantemente.",
      "Vierte el caldo de vegetales y deja hervir.",
      "Reduce el fuego y cocina tapado por 15-18 minutos, hasta que la zanahoria esté muy suave.",
      "Licúa la mezcla hasta lograr una crema homogénea y ajusta la sal.",
      "Sirve tibia, no caliente, para mayor comodidad al comer.",
    ],
  },
  {
    id: 3,
    nombre: "Puré de camote y manzana",
    categoria: "Guarniciones y purés",
    publico: true,
    icono: "🍠",
    tiempo: "20 min",
    porciones: 2,
    dificultad: "Fácil",
    descripcion:
      "Puré dulce y suave, fácil de digerir y rico en vitaminas.",
    beneficio:
      "Alto en vitamina A y fibra soluble, suave para el sistema digestivo.",
    ingredientes: [
      "2 camotes medianos, pelados y cortados en cubos",
      "1 manzana pelada y cortada en cubos",
      "1/2 taza de agua",
      "1 cucharadita de canela en polvo",
      "1 cucharadita de mantequilla o aceite de oliva (opcional)",
    ],
    pasos: [
      "Coloca los cubos de camote y manzana en una olla con el agua.",
      "Cocina a fuego medio, tapado, durante 15 minutos o hasta que estén muy suaves.",
      "Escurre el exceso de agua si es necesario.",
      "Machaca o licúa hasta obtener un puré suave y sin grumos.",
      "Agrega la canela y la mantequilla, y mezcla bien.",
      "Sirve tibio en porciones pequeñas.",
    ],
  },
  {
    id: 4,
    nombre: "Batido verde de espinaca y piña",
    categoria: "Batidos y bebidas",
    publico: false,
    icono: "🥬",
    tiempo: "5 min",
    porciones: 1,
    dificultad: "Fácil",
    descripcion:
      "Bebida refrescante cargada de antioxidantes y vitaminas.",
    beneficio:
      "Rica en vitamina C y antioxidantes que apoyan el sistema inmunológico.",
    ingredientes: [
      "1 taza de espinaca fresca",
      "1 taza de piña picada",
      "1/2 pepino pelado",
      "1 taza de agua fría o agua de coco",
      "1 cucharadita de miel (opcional)",
    ],
    pasos: [
      "Lava bien la espinaca y el pepino.",
      "Coloca todos los ingredientes en la licuadora.",
      "Licúa hasta que la mezcla esté completamente suave.",
      "Cuela si se prefiere una textura más ligera.",
      "Sirve inmediatamente para conservar los nutrientes.",
    ],
  },
  {
    id: 5,
    nombre: "Crema de pollo y vegetales",
    categoria: "Sopas y cremas",
    publico: false,
    icono: "🍗",
    tiempo: "35 min",
    porciones: 3,
    dificultad: "Media",
    descripcion:
      "Plato suave y nutritivo, con proteína de fácil digestión.",
    beneficio:
      "Aporta proteína magra esencial para mantener la masa muscular durante el tratamiento.",
    ingredientes: [
      "1 pechuga de pollo sin piel, cocida y desmenuzada",
      "1 papa mediana picada",
      "1 zanahoria picada",
      "1/2 taza de calabacín picado",
      "2 tazas de caldo de pollo bajo en sodio",
      "1/4 taza de leche o crema light",
    ],
    pasos: [
      "Cocina la papa, la zanahoria y el calabacín en el caldo de pollo hasta que estén blandos, unos 15 minutos.",
      "Licúa los vegetales cocidos junto con el caldo hasta obtener una crema suave.",
      "Regresa la crema a la olla y añade el pollo desmenuzado.",
      "Incorpora la leche o crema light y cocina a fuego bajo por 5 minutos más, sin dejar hervir.",
      "Ajusta la sal con moderación y sirve tibia.",
    ],
  },
  {
    id: 6,
    nombre: "Yogur con moras y semillas de chía",
    categoria: "Snacks y postres",
    publico: true,
    icono: "🫐",
    tiempo: "5 min",
    porciones: 1,
    dificultad: "Fácil",
    descripcion:
      "Snack refrescante rico en probióticos y fibra.",
    beneficio:
      "Los probióticos ayudan a la salud digestiva y las semillas de chía aportan omega-3.",
    ingredientes: [
      "1 taza de yogur natural sin azúcar",
      "1/2 taza de moras (frescas o congeladas)",
      "1 cucharada de semillas de chía",
      "1 cucharadita de miel (opcional)",
    ],
    pasos: [
      "Coloca el yogur en un tazón o vaso.",
      "Agrega las moras encima.",
      "Espolvorea las semillas de chía.",
      "Añade miel al gusto si se desea un toque más dulce.",
      "Deja reposar 5 minutos para que la chía se hidrate un poco antes de servir.",
    ],
  },
  {
    id: 7,
    nombre: "Arroz con lentejas y calabaza",
    categoria: "Platos fuertes",
    publico: true,
    icono: "🍛",
    tiempo: "40 min",
    porciones: 4,
    dificultad: "Media",
    descripcion:
      "Plato completo, suave y rico en proteína vegetal y fibra.",
    beneficio:
      "Combina proteína vegetal con fibra suave, fácil de digerir en porciones moderadas.",
    ingredientes: [
      "1 taza de arroz",
      "1 taza de lentejas cocidas",
      "1 taza de calabaza pelada y cortada en cubos",
      "1/2 cebolla picada",
      "1 diente de ajo picado",
      "2 cucharadas de aceite de oliva",
      "2 tazas de caldo de vegetales",
    ],
    pasos: [
      "Sofríe la cebolla y el ajo en aceite de oliva hasta que estén dorados.",
      "Agrega la calabaza y cocina por 3 minutos.",
      "Incorpora el arroz y mezcla bien con el sofrito.",
      "Vierte el caldo de vegetales y las lentejas cocidas.",
      "Cocina tapado a fuego bajo durante 18-20 minutos, hasta que el arroz esté tierno.",
      "Deja reposar 5 minutos antes de servir.",
    ],
  },
  {
    id: 8,
    nombre: "Salmón al vapor con brócoli",
    categoria: "Platos fuertes",
    publico: false,
    icono: "🐟",
    tiempo: "25 min",
    porciones: 2,
    dificultad: "Media",
    descripcion:
      "Plato ligero y nutritivo, cocido de forma suave para facilitar la digestión.",
    beneficio: "El salmón aporta omega-3 con propiedades antiinflamatorias.",
    ingredientes: [
      "2 filetes de salmón",
      "2 tazas de brócoli en floretes",
      "1 limón",
      "1 cucharada de aceite de oliva",
      "Sal y hierbas al gusto (moderado)",
    ],
    pasos: [
      "Coloca el salmón y el brócoli en una vaporera o cesta sobre agua hirviendo.",
      "Cocina al vapor durante 12-15 minutos, hasta que el salmón se desmenuce fácilmente.",
      "Retira con cuidado y coloca en un plato.",
      "Rocía con aceite de oliva y jugo de limón fresco.",
      "Sazona ligeramente con sal y hierbas antes de servir.",
    ],
  },
  {
    id: 9,
    nombre: "Gelatina de frutas naturales con agua de coco",
    categoria: "Snacks y postres",
    publico: false,
    icono: "🍇",
    tiempo: "10 min + reposo",
    porciones: 4,
    dificultad: "Fácil",
    descripcion:
      "Postre ligero e hidratante, ideal en días de poco apetito.",
    beneficio: "Ayuda a mantener la hidratación y es suave para el estómago.",
    ingredientes: [
      "2 tazas de agua de coco",
      "1 sobre de grenetina o agar-agar sin sabor",
      "1 taza de fruta picada (mango, fresa o durazno)",
      "1 cucharada de miel (opcional)",
    ],
    pasos: [
      "Hidrata la grenetina siguiendo las instrucciones del empaque.",
      "Calienta el agua de coco sin dejar hervir y disuelve la grenetina hidratada.",
      "Añade la miel si se desea más dulzor.",
      "Distribuye la fruta picada en moldes individuales.",
      "Vierte la mezcla de agua de coco sobre la fruta.",
      "Refrigera por al menos 3 horas o hasta que cuaje por completo.",
    ],
  },
  {
    id: 10,
    nombre: "Té de jengibre y limón con miel",
    categoria: "Batidos y bebidas",
    publico: false,
    icono: "🍵",
    tiempo: "10 min",
    porciones: 1,
    dificultad: "Fácil",
    descripcion:
      "Infusión cálida y reconfortante para aliviar molestias estomacales.",
    beneficio:
      "El jengibre y el limón son tradicionalmente usados para aliviar náuseas leves.",
    ingredientes: [
      "1 taza de agua",
      "1 cucharadita de jengibre fresco rallado",
      "El jugo de medio limón",
      "1 cucharadita de miel",
    ],
    pasos: [
      "Hierve el agua junto con el jengibre rallado durante 5 minutos.",
      "Retira del fuego y deja reposar 2 minutos.",
      "Cuela la infusión en una taza.",
      "Añade el jugo de limón y la miel, mezclando bien.",
      "Bebe tibio, en sorbos pequeños.",
    ],
  },
  {
    id: 11,
    nombre: "Puré de manzana y pera",
    categoria: "Guarniciones y purés",
    publico: false,
    icono: "🍏",
    tiempo: "20 min",
    porciones: 2,
    dificultad: "Fácil",
    descripcion:
      "Puré suave y ligeramente dulce, fácil de digerir entre comidas.",
    beneficio:
      "Aporta fibra soluble y es suave para el estómago en días de poco apetito.",
    ingredientes: [
      "2 manzanas peladas y cortadas en cubos",
      "2 peras peladas y cortadas en cubos",
      "1/2 taza de agua",
      "1 rama de canela",
      "1 cucharadita de miel (opcional)",
    ],
    pasos: [
      "Coloca la manzana, la pera, el agua y la canela en una olla.",
      "Cocina a fuego medio, tapado, durante 12-15 minutos hasta que la fruta esté muy suave.",
      "Retira la rama de canela.",
      "Machaca o licúa hasta obtener un puré homogéneo.",
      "Agrega miel al gusto y sirve tibio.",
    ],
  },
  {
    id: 12,
    nombre: "Batido de mango y yogur",
    categoria: "Batidos y bebidas",
    publico: false,
    icono: "🥭",
    tiempo: "5 min",
    porciones: 1,
    dificultad: "Fácil",
    descripcion:
      "Batido cremoso y refrescante, rico en vitaminas y probióticos.",
    beneficio:
      "El mango aporta vitamina C y el yogur ayuda a la salud digestiva.",
    ingredientes: [
      "1 taza de mango maduro picado",
      "1 taza de yogur natural sin azúcar",
      "1/2 taza de agua fría o hielo",
      "1 cucharadita de miel (opcional)",
    ],
    pasos: [
      "Coloca el mango, el yogur y el agua en la licuadora.",
      "Licúa hasta obtener una mezcla suave y sin grumos.",
      "Agrega miel si se desea más dulzor y licúa unos segundos más.",
      "Sirve inmediatamente en un vaso.",
    ],
  },
  {
    id: 13,
    nombre: "Crema de calabaza y coco",
    categoria: "Sopas y cremas",
    publico: false,
    icono: "🎃",
    tiempo: "30 min",
    porciones: 3,
    dificultad: "Media",
    descripcion:
      "Crema suave y aromática, reconfortante para días de poco apetito.",
    beneficio:
      "La calabaza aporta vitamina A y el coco brinda energía de fácil digestión.",
    ingredientes: [
      "3 tazas de calabaza pelada y cortada en cubos",
      "1/2 cebolla picada",
      "1 taza de leche de coco",
      "1 taza de caldo de vegetales bajo en sodio",
      "1 cucharada de aceite de oliva",
      "Sal al gusto (moderada)",
    ],
    pasos: [
      "Sofríe la cebolla en el aceite de oliva hasta que esté transparente.",
      "Agrega la calabaza y cocina 2 minutos moviendo constantemente.",
      "Vierte el caldo de vegetales y cocina tapado 15 minutos, hasta que la calabaza esté muy suave.",
      "Licúa junto con la leche de coco hasta obtener una crema homogénea.",
      "Regresa a la olla, ajusta la sal y calienta 2 minutos más sin hervir.",
      "Sirve tibia.",
    ],
  },
  {
    id: 14,
    nombre: "Pechuga de pollo al horno con puré de papa",
    categoria: "Platos fuertes",
    publico: false,
    icono: "🍽️",
    tiempo: "45 min",
    porciones: 3,
    dificultad: "Media",
    descripcion:
      "Plato completo y suave, con proteína magra y un acompañamiento cremoso.",
    beneficio:
      "Aporta proteína de fácil digestión, clave para mantener la masa muscular durante el tratamiento.",
    ingredientes: [
      "2 pechugas de pollo sin piel",
      "3 papas medianas peladas",
      "1/4 taza de leche",
      "1 cucharada de aceite de oliva",
      "Hierbas al gusto (romero o perejil)",
      "Sal al gusto (moderada)",
    ],
    pasos: [
      "Precalienta el horno a 180°C.",
      "Coloca el pollo en una charola, rocía con aceite de oliva y hierbas, y hornea 25-30 minutos hasta que esté bien cocido.",
      "Mientras tanto, cocina las papas en agua hirviendo hasta que estén suaves, unos 20 minutos.",
      "Escurre las papas y machácalas con la leche hasta obtener un puré suave.",
      "Corta el pollo en trozos pequeños o desmenúzalo si hay dificultad para masticar.",
      "Sirve el pollo acompañado del puré tibio.",
    ],
  },
  {
    id: 15,
    nombre: "Compota de durazno con avena",
    categoria: "Snacks y postres",
    publico: false,
    icono: "🍑",
    tiempo: "15 min",
    porciones: 2,
    dificultad: "Fácil",
    descripcion:
      "Postre tibio y suave, ideal como snack nutritivo entre comidas.",
    beneficio:
      "Combina fibra soluble de la avena con vitaminas del durazno, suave para el estómago.",
    ingredientes: [
      "2 duraznos maduros, pelados y picados",
      "1/2 taza de avena cocida",
      "1/2 taza de agua",
      "1 cucharadita de canela en polvo",
      "1 cucharadita de miel (opcional)",
    ],
    pasos: [
      "Coloca el durazno picado y el agua en una olla pequeña.",
      "Cocina a fuego medio durante 8-10 minutos, hasta que el durazno esté muy suave.",
      "Machaca ligeramente con un tenedor para lograr una textura de compota.",
      "Incorpora la avena cocida y la canela, mezclando bien.",
      "Agrega miel al gusto y sirve tibio.",
    ],
  },
];
